version: '3'

services:
  llm-platform:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - API_KEY=sk-Pb986eUQIj2VFlHy7mMd5g
      - API_URL=https://llmapi.paratera.com
      - PORT=3000
    restart: unless-stopped
